# Generated by Django 3.1.2 on 2024-11-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
                ('code', models.CharField(max_length=15, null=True)),
                ('web_site', models.CharField(max_length=500, null=True)),
                ('attribute_1', models.CharField(max_length=500, null=True)),
                ('attribute_2', models.CharField(max_length=500, null=True)),
                ('attribute_3', models.CharField(max_length=500, null=True)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.IntegerField(null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
