# Generated by Django 3.1.2 on 2024-11-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
