# Generated by Django 3.1.2 on 2024-11-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_university_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
