# Generated by Django 3.1.2 on 2024-11-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_university_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='programs',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='success_number',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
