# Generated by Django 3.1.2 on 2024-12-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_auto_20241129_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('whatsapp', models.CharField(max_length=50, null=True)),
                ('program', models.IntegerField(null=True)),
                ('subject', models.CharField(max_length=15, null=True)),
                ('qualification', models.CharField(max_length=5000, null=True)),
                ('attribute_1', models.CharField(max_length=500, null=True)),
                ('attribute_2', models.CharField(max_length=500, null=True)),
                ('attribute_3', models.CharField(max_length=500, null=True)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.IntegerField(null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
