# Generated by Django 3.1.2 on 2024-12-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_client_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
